typography_spectrum: 0.7932290507014841
color:
  brandStrength: 0.003415871411561966
  lightness: 0.569100966444239
  saturation: 0.7260364140383899
  rhythmicContrast: 0.4493723935447633
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
opengraph:
  image: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/e491c165-9550-4c6a-b72a-820d9f36a23e.jpg'
layout_spectrum: 0.36304314248263836
author:
  name: DE-PHOTOGRAPHY.NET
  email: diederick@de-photography.net
  url: www.de-photography.net
logo: null
name: DE-PHOTOGRAPHY
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/c639c194-251e-4738-81aa-3331c920eafb.jpg'
title: Property and interior Photography Professionals
